name: AdvEverCart
main: com.sparkedia.valrix.evercart.EverCart
version: 2.0.0
authors: [Valrix, AgentME, zhuowei, Dragobar]
description: Allows minecarts to move in uninhabited parts of the map to move goods, mobs, villagers and more to distant places and players.
commands:
    evercart:
        description: The mina EverCart command.
        permission: evercart
        usage: /<command> 
permissions: 
    evercart:
    	description: Gives access to the evercart toggle system.
    	